### ISSUE TITLE
Instantiating BazzarSignInClient using Context instead of Activity

### ISSUE THREAD

**Issue by AliBagherifam** [cafebazaar/CafeBazaarAuth#11]
`BazzarSignInClient` has `Activity` as a constructor parameter which only used to fetch package name of the application.
With the fact that `Activity.packageName` directly calls `Context.PackageName` in the internal, it would be better to use `Context` as type of the constructor parameter. Providing `Activity` for instantiating the class, could be hard in some situations.

**Comment by shayanpourvatan** [comment]
Thanks Ali for your feedback.

You are completely right, we will fix this issue in next release
Fix in [This MR](https://github.com/cafebazaar/CafeBazaarAuth/pull/13)
