### ISSUE TITLE
startActivityForResult has been deprecated

### ISSUE THREAD

**Issue by AliBagherifam** [cafebazaar/CafeBazaarAuth#12]
Starting from AndroidX [Activity 1.2.0-alpha04](https://developer.android.com/jetpack/androidx/releases/activity#1.2.0-alpha04) and [Fragment 1.3.0-alpha04](https://developer.android.com/jetpack/androidx/releases/fragment#1.3.0-alpha04), the `startActivityForResult()` / `onActivityResult()` and `onRequestPermissionsResult()` APIs been deprecated and using Activity Result APIs, is the recommended way.

It could be nice if library provides a built-in `ActivityResultContract` class which can be used with `registerForActivityResult()`. Something like this:

```
class BazaarLoginContract : ActivityResultContract<Activity, BazaarSignInAccount?>() {

    override fun createIntent(context: Context, input: Activity): Intent {
        val signInOption = BazaarSignInOptions
            .Builder(SignInOption.DEFAULT_SIGN_IN)
            .build()

        val client = BazaarSignIn.getClient(
            input,
            signInOption
        )

        return client.getSignInIntent()
    }

    override fun parseResult(resultCode: Int, intent: Intent?): BazaarSignInAccount? =
        BazaarSignIn.getSignedInAccountFromIntent(intent)
}
```

Then inside an `Activity`:
```
val loginThroughBazaar = 
      registerForActivityResult(BazaarLoginContract()) { signInAccount: BazaarSignInAccount? ->
          // Handle the Sign-In info
      }

override fun onCreate(savedInstanceState: Bundle?) {
    // ...

    val loginButton = findViewById<Button>(R.id.login_button)

    loginButton .setOnClickListener {
        // Pass in the activity as the input
        loginThroughBazaar.launch(this)
    }
}
```

**Comment by AliBagherifam** [comment]
Also if issue #11 is fixed, the `Activity` input parameter could be removed (replaced with `Unit`) from `ActivityResultContract`.

```
class BazaarLoginContract : ActivityResultContract<Unit, BazaarSignInAccount?>() {

    override fun createIntent(context: Context, input: Unit): Intent {
        // ...

        val client = BazaarSignIn.getClient(
            context,
            signInOption
        )

       // ...
    }
   
    // ...
}
```

Then inside `Activity`, the `ActivityResultLauncher` can be called using this shiny built-in extension function:

```
loginThroughBazaar.launch()
```

**Comment by shayanpourvatan** [comment]
Thanks Ali for your feedback, As the library that you mentioned, released in beta version in this day, It is not recommended to used in production library, but we consider this changes and apply this as soon as the library release in stable version.
