### ISSUE TITLE
BazaarSignIn.getLastSignedInAccountSync throw exception

### ISSUE THREAD

**Issue by omidfaraji** [cafebazaar/CafeBazaarAuth#14]
Hi,
BazaarSignIn.getLastSignedInAccountSync method does not work in none of background and main threads,
Check once by your self.

Exceptions:
IllegalStateException: Can't call this method on UI thread
and
IllegalStateException: Cannot invoke observe on a background thread

**Comment by shayanpourvatan** [comment]
We're working on it, Fixed in [this PR](https://github.com/cafebazaar/CafeBazaarAuth/pull/16). This issue will fix in the next release

**Comment by shayanpourvatan** [comment]
This issue fixed in `alpha07`

**Comment by omidfaraji** [comment]
Where is version alpha07?
I can't see it

**Comment by shayanpourvatan** [comment]
alpha06, sorry for the mistake

**Comment by omidfaraji** [comment]
In alpha06 the problem still exists

**Comment by omidfaraji** [comment]
Yes. now it's work. 
Thank you
