### ISSUE TITLE
Is needed to update always returns true 

### ISSUE THREAD

**Issue by arsamme** [cafebazaar/CafeBazaarAuth#17]
isNeededToUpdateBazaar always returns true for both 
auth and storage

**Comment by hamidrezasahraei** [comment]
@arsamme 
Can you provide more information, such as the Bazaar client versions that you have tested your application with them and the SDK version?

**Comment by arsamme** [comment]
> @arsamme
> Can you provide more information, such as the Bazaar client versions that you have tested your application with them and the SDK version?

I've 1000100 version of Bazaar installed on my device. My phones Android version is 11 and application's target SDK is 30.

**Comment by shayanpourvatan** [comment]
@arsamme Can you call the following function and see the result?

```
fun getPackageInfo(context: Context): Long = try {
    val packageManager = context.packageManager
    packageManager.getPackageInfo("com.farsitel.bazaar", 0)
} catch (e: Exception) {
    null
}?.versionCode
```

**Comment by arsamme** [comment]
I tried this.
It returns null, then I checked catch and noticed that is throws `NameNotFoundException` exception.

I found this :
[Package visibility in Android 11](https://developer.android.com/about/versions/11/privacy/package-visibility)

Then added `<queries>` in manifest:
```
<queries>
          <package android:name="com.farsitel.bazaar" />
</queries>

```

Now It works and returns 1000100 :))

**Comment by shayanpourvatan** [comment]
@arsamme You can create PR for this issue, we will merge it in the next release version.

**Comment by arsamme** [comment]
@shayanpourvatan Done.

#19

**Comment by shayanpourvatan** [comment]
Merged
