### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by DeusExMachina1993** [cafebazaar/CafeBazaarAuth#20]
سلام
ارور
 Authentication failed 
 در یونیتی داده می شود دلیل این ارور چیست ؟
چند سوال
1-آيا نسخه اپليكيشن بايد با آخرين نسخه در بازار يكسان باشد؟
2-آياتعليق بودن برنامه مي تواند اين ارور را به وجود آورد ؟
`  BazaarGamesPlatform.Instance.Authenticate(false, (response,ss) =>...`
`12-31 00:20:55.724   974  9222 W ActivityManager: Service.startForeground() not allowed due to bg restriction: service com.farsitel.bazaar/.giant.login.ial.InAppLoginService
12-31 00:20:55.742   974  9222 W ActivityManager: Service.startForeground() not allowed due to bg restriction: service com.farsitel.bazaar/.giant.login.ial.InAppLoginService`

**Comment by mreram** [comment]
دلیل این محدودیت های اعمال شده توسط دستگاه هست که خود کاربر در تنظیمات باتری دستگاه این گزینه رو فعال کرده.
