### ISSUE TITLE
مشکل در SilentSignIn

### ISSUE THREAD

**Issue by armangames** [cafebazaar/CafeBazaarAuth#21]
در بعضی از گوشی ها فانکشین زیر عمل نمیکند
getLastSignedInAccount

دقیقتر توضیح بدم به این شکل است که در گوشی ریسنت اپ ها را ببندیم رم نیز خالی میشود و در ورود بعدی به بازی یا اپلیکیشنی که ورود با بازار درش پیاده سازی شده سایلنت ساین این ، دیگر کار نمیکند و فانکشینی که در بالا گفتم اصلن صدا زده نمیشود

در گوشی سامسونگ A50 
 شیائومی mi4i

بنده این مشکل را دیدم

**Comment by shayanpourvatan** [comment]
سلام آرمان.
ممنون از گزارش خطا، در حال بررسی و رفع این مشکل هستیم.

**Comment by mDadashi** [comment]
Hello. Did you solve this? I have the same issue. I have tested it on Xiaomi k20 pro (Mi 9 pro) with android 11 (MIUI 12.5.4)
Issue Details: 
- kill Bazaar from recent apps.
- Try to run getLastSignedInAccount. The callback never gets fired.

Sounds like the library can't access Bazaar's background service. There would be some configurable timeout at least for this method to return with some exception under unexpected circumstances. 
I am afraid without the issue solved, it would be difficult to use the service for signing users in.

**Comment by mhrohani1385** [comment]
این مشکل واقعا دردسر سازه تا جایی که من می دونم مشکل اجرای بازار در پس زمینه هست که الان من روی گوشی هواوی امتحان کردم به همین مشکل خوردم مجبور شدم قبل از اجرای برنامه کافه بازار رو باز کنم .

من کل برنامه رو بر این پایه نوشتم که کاربر با بازار وارد بشه این مشکل روی تجربه کاربری تاثیر به شدت بدی میزاره . شاید برای ادامه فعالیت سرویس بازار لازم باشه که یه نوتیفیکیشن قرار بدید که به بازار در این مودل ها که برای کاهش مصرف باتری و امنیت سرویس ها پس زمینه رو غیر فعال می کنند یک سرویس پیش زمینه داشته باشه .

اگر بشه موقتا یک روش بگید تا ما بتونیم قبل از اجرای اکتیویتی اصلی برنامه سرویس بازار در پس زمینه رو ریستارت کنیم موقتا حل میشه . با تشکر .

**Comment by mhrohani1385** [comment]
سلام و عرض خسته نباشید .
مشکل در نسخه جدید برنامه حل شده . بنده روی یک گوشی هوایی امتحان کردم .
در صورت نیاز این مشکل رو ببندید.

با تشکر
