### ISSUE TITLE
مشکل در <receiver> فایل manifest کتابخانه ورود با بازار

### ISSUE THREAD

**Issue by mhrohani1385** [cafebazaar/CafeBazaarAuth#28]
در اندروید دوازده برای امنیت اطلاعات باید خط زیر در تگ receiver فایل مانیفست کتابخانه تنظیم شود .

android:exported="true"

https://developer.android.com/guide/topics/manifest/activity-element#exported

> android:exported needs to be explicitly specified for <receiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

خواهشمندم این خطا را رفع کرده و بروزرسانی نمایید

لطفا جهت مشاهده تغییرات مورد نیاز در کد به لینک زیر مراجعه نمایید :
https://github.com/cafebazaar/CafeBazaarAuth/pull/29/commits/1819887a7aa2f618e62ac03f398b2cfa06df274e

در صورتی که true قرار دهید این receiver خواهد توانست با دیگر اپلیکیشن ها ارتباط داشته و از دیگر اپلیکیشن ها داده دریافت نماید

**Comment by shayanpourvatan** [comment]
به زودی اصلاح میشه و نسخه‌ی جدید ارائه می‌گردد

**Comment by mhrohani1385** [comment]
با تشکر

**Comment by mreram** [comment]
Fixed in 1.0.0beta01 version
