### ISSUE TITLE
خطا بعد از تایید دسترسی برنامه به ورود با بازار

### ISSUE THREAD

**Issue by mhrohani1385** [cafebazaar/CafeBazaarAuth#33]
```E/BazaarInAppLogin: In-app login error: Account not exists for packageName```

model : samsung
android : 6
---------------------
model : nox
android : 9
---------------------
bazaar version : current date latest version

**Comment by DHosseiny** [comment]
Please add more info to this issue. What packagename you are testing with?

**Comment by DHosseiny** [comment]
I am closing this. feel free to reopen it if its not fixed.
